### ISSUE TITLE
Numpy version error

### ISSUE THREAD

**Issue by methyllorange** [mggg/ecological-inference#109]
There is dependency problem with the NumPy package

**Comment by pjrule** [comment]
Hi, @methyllorange! Would you mind posting specific details about the error you're encountering (e.g. the full error message)?

**Comment by methyllorange** [comment]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pymc 5.2.0 requires arviz>=0.13.0, but you have arviz 0.12.1 which is incompatible.

This is the error when I get from cmd when ı try to pip install the package and when I try to solve by dowlonding the relevant packages it starts to loop hole. That between dependency problem between pmc3 and pyei and I think the main problem is bool operator that you used in numpy package is only availible before 12.0 version of the numpy and but pymc requires higher version of the numpy package.

**Comment by karink520** [comment]
Seeing this issue from a while ago. The current version of pyei runs on pymc v4, so trying to run on pymc 5.2.0 would currently cause issues. Can you switch to pymc v4? I'm going to close this issue for now since I'm not seeing problems pip installing into a fresh environment, but feel free to reopen if you're still running into issues and it's still relevant.
